// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4nASvwAKi3fxQzXWjr2DjzAAJ34OASRA',
    authDomain: 'lalago-v2.firebaseapp.com',
    projectId: 'lalago-v2',
    storageBucket: 'lalago-v2.firebasestorage.app',
    messagingSenderId: '916084329397',
    appId: '1:916084329397:web:1c27fc',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4nASvwAKi3fxQzXWjr2DjzAAJ34OASRA',
    authDomain: 'lalago-v2.firebaseapp.com',
    projectId: 'lalago-v2',
    storageBucket: 'lalago-v2.firebasestorage.app',
    messagingSenderId: '916084329397',
    appId: '1:916084329397:android:58c2f09244d7ccbe1c27fc',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4nASvwAKi3fxQzXWjr2DjzAAJ34OASRA',
    authDomain: 'lalago-v2.firebaseapp.com',
    projectId: 'lalago-v2',
    storageBucket: 'lalago-v2.firebasestorage.app',
    messagingSenderId: '916084329397',
    appId: '1:916084329397:ios:1c27fc',
    iosBundleId: 'com.lalago.admin',
  );
}
