platform :ios, '16.0'

ENV['COCOAPODS_DISABLE_STATS'] = 'true'
require 'fileutils'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(
    File.join('..', 'Flutter', 'Generated.xcconfig'),
    __FILE__,
  )
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. " \
      "If you're running pod install manually, make sure " \
      "flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. " \
    "Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(
  File.join('packages', 'flutter_tools', 'bin', 'podhelper'),
  flutter_root,
)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks! :linkage => :static

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)

    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'x86_64'
      config.build_settings['CODE_SIGNING_ALLOWED[sdk=iphonesimulator*]'] = 'NO'
      config.build_settings['CODE_SIGNING_REQUIRED[sdk=iphonesimulator*]'] = 'NO'
      config.build_settings['CODE_SIGN_IDENTITY[sdk=iphonesimulator*]'] = ''
      config.build_settings[
        'CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'
      ] = 'YES'
      config.build_settings[
        'CLANG_WARN_NON_MODULAR_INCLUDE_IN_FRAMEWORK_MODULE'
      ] = 'NO'
      config.build_settings[
        'CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER'
      ] = 'NO'

      other_cflags = config.build_settings['OTHER_CFLAGS'] || '$(inherited)'
      non_modular_flags =
        '-Wno-non-modular-include-in-framework-module ' \
        '-Wno-error=non-modular-include-in-framework-module'
      unless other_cflags.include?(non_modular_flags)
        config.build_settings['OTHER_CFLAGS'] =
          "#{other_cflags} #{non_modular_flags}"
      end
      quoted_include_flag = '-Wno-quoted-include-in-framework-header'
      unless other_cflags.include?(quoted_include_flag)
        config.build_settings['OTHER_CFLAGS'] =
          "#{config.build_settings['OTHER_CFLAGS']} #{quoted_include_flag}"
      end

      other_cxxflags =
        config.build_settings['OTHER_CPLUSPLUSFLAGS'] || '$(inherited)'
      unless other_cxxflags.include?(non_modular_flags)
        config.build_settings['OTHER_CPLUSPLUSFLAGS'] =
          "#{other_cxxflags} #{non_modular_flags}"
      end
      unless other_cxxflags.include?(quoted_include_flag)
        config.build_settings['OTHER_CPLUSPLUSFLAGS'] =
          "#{config.build_settings['OTHER_CPLUSPLUSFLAGS']} #{quoted_include_flag}"
      end
    end

    if target.name == 'BoringSSL-GRPC'
      target.source_build_phase.files.each do |file|
        next unless file.settings && file.settings['COMPILER_FLAGS']

        flags = file.settings['COMPILER_FLAGS'].split
        flags.reject! { |flag| flag == '-GCC_WARN_INHIBIT_ALL_WARNINGS' }
        file.settings['COMPILER_FLAGS'] = flags.join(' ')
      end
    end

    if target.name.start_with?('firebase_')
      target.build_configurations.each do |config|
        other_cflags = config.build_settings['OTHER_CFLAGS'] || '$(inherited)'
        modulemap_flag =
          '-fmodule-map-file=${PODS_ROOT}/Firebase/CoreOnly/Sources/module.modulemap'
        unless other_cflags.include?(modulemap_flag)
          config.build_settings['OTHER_CFLAGS'] =
            "#{other_cflags} #{modulemap_flag}"
        end

        other_cxxflags =
          config.build_settings['OTHER_CPLUSPLUSFLAGS'] || '$(inherited)'
        unless other_cxxflags.include?(modulemap_flag)
          config.build_settings['OTHER_CPLUSPLUSFLAGS'] =
            "#{other_cxxflags} #{modulemap_flag}"
        end
      end
    end

  end

  basic_seq_paths = [
    File.join(
      installer.sandbox.root,
      'gRPC-Core',
      'src',
      'core',
      'lib',
      'promise',
      'detail',
      'basic_seq.h',
    ),
    File.join(
      installer.sandbox.root,
      'gRPC-C++',
      'src',
      'core',
      'lib',
      'promise',
      'detail',
      'basic_seq.h',
    ),
  ]
  basic_seq_paths.each do |basic_seq_path|
    next unless File.exist?(basic_seq_path)

    FileUtils.chmod('u+w', basic_seq_path)
    contents = File.read(basic_seq_path)
    contents = contents.gsub(
      'Traits::CheckResultAndRunNext',
      'Traits::template CheckResultAndRunNext',
    )
    contents = contents.gsub(
      'Traits::template CallSeqFactory',
      'Traits::CallSeqFactory',
    )
    File.write(basic_seq_path, contents)
  end

  pub_cache_root = File.expand_path('~/.pub-cache/hosted/pub.dev')
  firebase_plugin_dirs = Dir.glob(File.join(pub_cache_root, 'firebase_*'))
  firebase_plugin_dirs.each do |dir|
    Dir.glob(File.join(dir, 'ios', 'Classes', '**', '*.{h,m}')).each do |file|
      contents = File.read(file)
      next unless contents.include?('#import <Firebase/Firebase.h>')

      contents = contents.gsub(
        '#import <Firebase/Firebase.h>',
        '@import Firebase;',
      )
      File.write(file, contents)
    end
  end

  firebase_modulemap = File.join(
    installer.sandbox.root,
    'Firebase',
    'CoreOnly',
    'Sources',
    'module.modulemap',
  )
  FileUtils.mkdir_p(File.dirname(firebase_modulemap))
  File.write(
    firebase_modulemap,
    <<~MODULEMAP,
      module Firebase {
        export *
        header "Firebase.h"
      }
    MODULEMAP
  )

  sqflite_umbrella = File.join(
    installer.sandbox.root,
    'Target Support Files',
    'sqflite_darwin',
    'sqflite_darwin-umbrella.h',
  )
  if File.exist?(sqflite_umbrella)
    contents = File.read(sqflite_umbrella)
    contents = contents.gsub(
      '#import "SqfliteImportPublic.h"',
      '#import <sqflite_darwin/SqfliteImportPublic.h>',
    )
    contents = contents.gsub(
      '#import "SqflitePluginPublic.h"',
      '#import <sqflite_darwin/SqflitePluginPublic.h>',
    )
    File.write(sqflite_umbrella, contents)
  end
end
